### ISSUE TITLE
Bug in layout on event page 

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#559]
1. grey zone (to use same layout that the one for notification part)
2. double line??
3. text not squeeze to the zone

**Comment by mehrdadgit** [comment]
Note (1) has been fixed in #557 and https://github.com/MSFREACH/msf-reach/commit/1d7ce72a694f40e77ac2dd040db8e26781c8fedf

And (2) should be the result of scrollbar enabling in #557 and https://github.com/MSFREACH/msf-reach/commit/b487af4cef3cc5a1fe097ace3bdc7455f536bae7 can be reversed

I remember fixing (3) in #535 https://github.com/MSFREACH/msf-reach/commit/856329c85a05a538412dcfd82064ff8a9a494fc8 apparently it is lost now due to merge conflict resolutions...needs to be redone (easy -> colspan=2)

**Comment by matthewberryman** [comment]
@mehrdadgit re https://github.com/MSFREACH/msf-reach/commit/856329c85a05a538412dcfd82064ff8a9a494fc8 I found that trick wasn't handling long notifications properly either so I didn't worry too much about that in the merge (my work on that aspect). Feel free to have a quick go if you have time.

**Comment by mehrdadgit** [comment]
(3) done @matthewberryman

**Comment by matthewberryman** [comment]
thanks. I tried reverting https://github.com/MSFREACH/msf-reach/commit/b487af4cef3cc5a1fe097ace3bdc7455f536bae7 locally and it didn't solve the double lines. I think some css styling for tab-panes on events page to make them take the same space as the surrounding `<div id="eventVApp">` should fix the double line issue?

@LucieGueuning the rest of the issues are fixed in dev test and prod now.

**Comment by mehrdadgit** [comment]
@matthewberryman @LucieGueuning  if I understand correctly, we mean double "vertical" lines? I propose we keep them as their current state; they show a number of panels are inside a container in which they can be scrolled. if we push them to edges the panel headers will lose their shape IMO.

**Comment by matthewberryman** [comment]
good point

**Comment by matthewberryman** [comment]
I have fixed an issue where long sharepoint links could break the layout.

@LucieGueuning are we good to close this one now?

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/43909558-890f19bc-9bf2-11e8-9ee1-ca1d00a378ff.png)

**Comment by matthewberryman** [comment]
@mehrdadgit there are still cases where there are URLs in notifications and it's wrapping properly (e.g. event ID 59 in prod)

**Comment by mehrdadgit** [comment]
on dev @matthewberryman
